apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lab2.fullname" . }}-credentials 
  labels:
    {{- include "lab2.labels" . | nindent 4 }}
type: Opaque
data:
  password: "{{ .Values.password | toString | b64enc }}"