name: Python CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/app_python/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Dependencies
      run: |
        cd app_python
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Linter
      run: |
        cd app_python
        pip install flake8
        flake8 .
    
    - name: Tests
      run: |
        python -m unittest discover -s app_python/tests
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        cd app_python
        docker build -t lab3:latest .
    - name: Push Docker image
      run: |
        docker tag lab2:latest ${{ secrets.DOCKERHUB_USERNAME }}/lab2:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/lab2:latest
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/app_python/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Dependencies
      run: |
        cd app_python
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Copy requirements.txt
      run: |
        cp app_python/requirements.txt requirements.txt
